package io.github.masyumero.morethermalevaporationcompat.common.registries;

import io.github.masyumero.morethermalevaporationcompat.MoreThermalEvaporationCompat;
import io.github.masyumero.morethermalevaporationcompat.evolved.common.tile.multiblock.TileEntityOverclockedThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.evolved.common.tile.multiblock.TileEntityDenseThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.evolved.common.tile.multiblock.TileEntityMultiversalThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.evolved.common.tile.multiblock.TileEntityQuantumThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.extras.common.tile.multiblock.TileEntityAbsoluteThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.extras.common.tile.multiblock.TileEntityCosmicThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.extras.common.tile.multiblock.TileEntityInfiniteThermalEvaporationController;
import io.github.masyumero.morethermalevaporationcompat.extras.common.tile.multiblock.TileEntitySupremeThermalEvaporationController;
import mekanism.common.inventory.container.tile.MekanismTileContainer;
import mekanism.common.registration.impl.ContainerTypeDeferredRegister;
import mekanism.common.registration.impl.ContainerTypeRegistryObject;

public class MoreThermalEvaporationCompatContainerTypes {
    public static final ContainerTypeDeferredRegister EVOLVED_CONTAINER_TYPES = new ContainerTypeDeferredRegister(MoreThermalEvaporationCompat.MODID);
    public static final ContainerTypeDeferredRegister EXTRAS_CONTAINER_TYPES = new ContainerTypeDeferredRegister(MoreThermalEvaporationCompat.MODID);

    // Overclocked
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityOverclockedThermalEvaporationController>> OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER, TileEntityOverclockedThermalEvaporationController.class);

    // Quantum
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityQuantumThermalEvaporationController>> QUANTUM_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.QUANTUM_THERMAL_EVAPORATION_CONTROLLER, TileEntityQuantumThermalEvaporationController.class);

    // Dense
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityDenseThermalEvaporationController>> DENSE_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.DENSE_THERMAL_EVAPORATION_CONTROLLER, TileEntityDenseThermalEvaporationController.class);

    // Multiversal
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityMultiversalThermalEvaporationController>> MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER, TileEntityMultiversalThermalEvaporationController.class);

    // Absolute
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityAbsoluteThermalEvaporationController>> ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER, TileEntityAbsoluteThermalEvaporationController.class);

    // Supreme
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntitySupremeThermalEvaporationController>> SUPREME_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.SUPREME_THERMAL_EVAPORATION_CONTROLLER, TileEntitySupremeThermalEvaporationController.class);

    // Cosmic
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityCosmicThermalEvaporationController>> COSMIC_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.COSMIC_THERMAL_EVAPORATION_CONTROLLER, TileEntityCosmicThermalEvaporationController.class);

    // Infinite
    public static final ContainerTypeRegistryObject<MekanismTileContainer<TileEntityInfiniteThermalEvaporationController>> INFINITE_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_CONTAINER_TYPES.register(MoreThermalEvaporationCompatBlocks.INFINITE_THERMAL_EVAPORATION_CONTROLLER, TileEntityInfiniteThermalEvaporationController.class);

    private MoreThermalEvaporationCompatContainerTypes() {

    }
}
