package io.github.masyumero.morethermalevaporationcompat.common.registries;

import io.github.masyumero.morethermalevaporationcompat.common.content.blocktype.MTECompatBlockTypeTile;
import io.github.masyumero.morethermalevaporationcompat.common.tier.TETier;
import io.github.masyumero.morethermalevaporationcompat.common.tile.multiblock.*;
import io.github.masyumero.morethermalevaporationcompat.common.util.UpgradeUtils;
import mekanism.common.MekanismLang;
import mekanism.common.block.attribute.AttributeStateFacing;
import mekanism.common.block.attribute.Attributes;

public class MoreThermalEvaporationCompatBlockTypes {
    // Overclocked
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> OVERCLOCKED_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.OVERCLOCKED_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.OVERCLOCKED).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> OVERCLOCKED_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.OVERCLOCKED_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.OVERCLOCKED).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("OverclockedThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.OVERCLOCKED).withGui(() -> MoreThermalEvaporationCompatContainerTypes.OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("OverclockedThermalEvaporationController").build();

    // Quantum
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> QUANTUM_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.QUANTUM_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.QUANTUM).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> QUANTUM_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.QUANTUM_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.QUANTUM).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("QuantumThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> QUANTUM_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.QUANTUM_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.QUANTUM).withGui(() -> MoreThermalEvaporationCompatContainerTypes.QUANTUM_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("QuantumThermalEvaporationController").build();

    // Dense
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> DENSE_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.DENSE_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.DENSE).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> DENSE_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.DENSE_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.DENSE).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("DenseThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> DENSE_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.DENSE_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.DENSE).withGui(() -> MoreThermalEvaporationCompatContainerTypes.DENSE_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("DenseThermalEvaporationController").build();

    // Multiversal
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> MULTIVERSAL_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.MULTIVERSAL_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.MULTIVERSAL).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> MULTIVERSAL_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.MULTIVERSAL_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.MULTIVERSAL).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("MultiversalThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.MULTIVERSAL).withGui(() -> MoreThermalEvaporationCompatContainerTypes.MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("MultiversalThermalEvaporationController").build();

    // Absolute
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> ABSOLUTE_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.ABSOLUTE_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.ABSOLUTE).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> ABSOLUTE_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.ABSOLUTE_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.ABSOLUTE).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("AbsoluteThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.ABSOLUTE).withGui(() -> MoreThermalEvaporationCompatContainerTypes.ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("AbsoluteThermalEvaporationController").build();

    // Supreme
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> SUPREME_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.SUPREME_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.SUPREME).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> SUPREME_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.SUPREME_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.SUPREME).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("SupremeThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> SUPREME_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.SUPREME_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.SUPREME).withGui(() -> MoreThermalEvaporationCompatContainerTypes.SUPREME_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("SupremeThermalEvaporationController").build();

    // Cosmic
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> COSMIC_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.COSMIC_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.COSMIC).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> COSMIC_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.COSMIC_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.COSMIC).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("CosmicThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> COSMIC_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.COSMIC_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.COSMIC).withGui(() -> MoreThermalEvaporationCompatContainerTypes.COSMIC_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("CosmicThermalEvaporationController").build();

    // Infinite
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationBlock> INFINITE_THERMAL_EVAPORATION_BLOCK = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.INFINITE_THERMAL_EVAPORATION_BLOCK, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_BLOCK, TETier.INFINITE).with(new Attributes.AttributeCustomResistance(9)).externalMultiblock().build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationValve> INFINITE_THERMAL_EVAPORATION_VALVE = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.INFINITE_THERMAL_EVAPORATION_VALVE, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_VALVE, TETier.INFINITE).with(Attributes.COMPARATOR, new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("InfiniteThermalEvaporationValve").build();
    public static final MTECompatBlockTypeTile<TileEntityTieredThermalEvaporationController> INFINITE_THERMAL_EVAPORATION_CONTROLLER = MTECompatBlockTypeTile.MTECompatBlockTileBuilder.createBlock(() -> MoreThermalEvaporationCompatTileEntityTypes.INFINITE_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.DESCRIPTION_THERMAL_EVAPORATION_CONTROLLER, TETier.INFINITE).withGui(() -> MoreThermalEvaporationCompatContainerTypes.INFINITE_THERMAL_EVAPORATION_CONTROLLER, MekanismLang.EVAPORATION_PLANT).withSupportedUpgrades(UpgradeUtils.getUpgrades()).with(Attributes.INVENTORY, Attributes.ACTIVE, new AttributeStateFacing(), new Attributes.AttributeCustomResistance(9)).externalMultiblock().withComputerSupport("InfiniteThermalEvaporationController").build();

    private MoreThermalEvaporationCompatBlockTypes() {
    }
}
