package io.github.masyumero.morethermalevaporationcompat.common.registries;

import io.github.masyumero.morethermalevaporationcompat.MoreThermalEvaporationCompat;
import io.github.masyumero.morethermalevaporationcompat.evolved.common.tile.multiblock.*;
import io.github.masyumero.morethermalevaporationcompat.extras.common.tile.multiblock.*;
import mekanism.common.registration.impl.TileEntityTypeDeferredRegister;
import mekanism.common.registration.impl.TileEntityTypeRegistryObject;
import mekanism.common.tile.base.TileEntityMekanism;

public class MoreThermalEvaporationCompatTileEntityTypes {
    public static final TileEntityTypeDeferredRegister EVOLVED_TILE_ENTITY_TYPES = new TileEntityTypeDeferredRegister(MoreThermalEvaporationCompat.MODID);
    public static final TileEntityTypeDeferredRegister EXTRAS_TILE_ENTITY_TYPES = new TileEntityTypeDeferredRegister(MoreThermalEvaporationCompat.MODID);

    // Overclocked
    public static final TileEntityTypeRegistryObject<TileEntityOverclockedThermalEvaporationBlock> OVERCLOCKED_THERMAL_EVAPORATION_BLOCK = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.OVERCLOCKED_THERMAL_EVAPORATION_BLOCK, TileEntityOverclockedThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityOverclockedThermalEvaporationValve> OVERCLOCKED_THERMAL_EVAPORATION_VALVE = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.OVERCLOCKED_THERMAL_EVAPORATION_VALVE, TileEntityOverclockedThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityOverclockedThermalEvaporationController> OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.OVERCLOCKED_THERMAL_EVAPORATION_CONTROLLER, TileEntityOverclockedThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Quantum
    public static final TileEntityTypeRegistryObject<TileEntityQuantumThermalEvaporationBlock> QUANTUM_THERMAL_EVAPORATION_BLOCK = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.QUANTUM_THERMAL_EVAPORATION_BLOCK, TileEntityQuantumThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityQuantumThermalEvaporationValve> QUANTUM_THERMAL_EVAPORATION_VALVE = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.QUANTUM_THERMAL_EVAPORATION_VALVE, TileEntityQuantumThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityQuantumThermalEvaporationController> QUANTUM_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.QUANTUM_THERMAL_EVAPORATION_CONTROLLER, TileEntityQuantumThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Dense
    public static final TileEntityTypeRegistryObject<TileEntityDenseThermalEvaporationBlock> DENSE_THERMAL_EVAPORATION_BLOCK = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.DENSE_THERMAL_EVAPORATION_BLOCK, TileEntityDenseThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityDenseThermalEvaporationValve> DENSE_THERMAL_EVAPORATION_VALVE = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.DENSE_THERMAL_EVAPORATION_VALVE, TileEntityDenseThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityDenseThermalEvaporationController> DENSE_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.DENSE_THERMAL_EVAPORATION_CONTROLLER, TileEntityDenseThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Multiversal
    public static final TileEntityTypeRegistryObject<TileEntityMultiversalThermalEvaporationBlock> MULTIVERSAL_THERMAL_EVAPORATION_BLOCK = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.MULTIVERSAL_THERMAL_EVAPORATION_BLOCK, TileEntityMultiversalThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityMultiversalThermalEvaporationValve> MULTIVERSAL_THERMAL_EVAPORATION_VALVE = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.MULTIVERSAL_THERMAL_EVAPORATION_VALVE, TileEntityMultiversalThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityMultiversalThermalEvaporationController> MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER = EVOLVED_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.MULTIVERSAL_THERMAL_EVAPORATION_CONTROLLER, TileEntityMultiversalThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Absolute
    public static final TileEntityTypeRegistryObject<TileEntityAbsoluteThermalEvaporationBlock> ABSOLUTE_THERMAL_EVAPORATION_BLOCK = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.ABSOLUTE_THERMAL_EVAPORATION_BLOCK, TileEntityAbsoluteThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityAbsoluteThermalEvaporationValve> ABSOLUTE_THERMAL_EVAPORATION_VALVE = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.ABSOLUTE_THERMAL_EVAPORATION_VALVE, TileEntityAbsoluteThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityAbsoluteThermalEvaporationController> ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.ABSOLUTE_THERMAL_EVAPORATION_CONTROLLER, TileEntityAbsoluteThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Supreme
    public static final TileEntityTypeRegistryObject<TileEntitySupremeThermalEvaporationBlock> SUPREME_THERMAL_EVAPORATION_BLOCK = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.SUPREME_THERMAL_EVAPORATION_BLOCK, TileEntitySupremeThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntitySupremeThermalEvaporationValve> SUPREME_THERMAL_EVAPORATION_VALVE = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.SUPREME_THERMAL_EVAPORATION_VALVE, TileEntitySupremeThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntitySupremeThermalEvaporationController> SUPREME_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.SUPREME_THERMAL_EVAPORATION_CONTROLLER, TileEntitySupremeThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Cosmic
    public static final TileEntityTypeRegistryObject<TileEntityCosmicThermalEvaporationBlock> COSMIC_THERMAL_EVAPORATION_BLOCK = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.COSMIC_THERMAL_EVAPORATION_BLOCK, TileEntityCosmicThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityCosmicThermalEvaporationValve> COSMIC_THERMAL_EVAPORATION_VALVE = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.COSMIC_THERMAL_EVAPORATION_VALVE, TileEntityCosmicThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityCosmicThermalEvaporationController> COSMIC_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.COSMIC_THERMAL_EVAPORATION_CONTROLLER, TileEntityCosmicThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);

    // Infinite
    public static final TileEntityTypeRegistryObject<TileEntityInfiniteThermalEvaporationBlock> INFINITE_THERMAL_EVAPORATION_BLOCK = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.INFINITE_THERMAL_EVAPORATION_BLOCK, TileEntityInfiniteThermalEvaporationBlock::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityInfiniteThermalEvaporationValve> INFINITE_THERMAL_EVAPORATION_VALVE = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.INFINITE_THERMAL_EVAPORATION_VALVE, TileEntityInfiniteThermalEvaporationValve::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
    public static final TileEntityTypeRegistryObject<TileEntityInfiniteThermalEvaporationController> INFINITE_THERMAL_EVAPORATION_CONTROLLER = EXTRAS_TILE_ENTITY_TYPES.register(MoreThermalEvaporationCompatBlocks.INFINITE_THERMAL_EVAPORATION_CONTROLLER, TileEntityInfiniteThermalEvaporationController::new, TileEntityMekanism::tickServer, TileEntityMekanism::tickClient);
}

